[package]
name = "the_glass_oak"
version = "0.1.0"
authors = ["Wyatt Carss <wyatt@wcarss.ca>"]

[dependencies]
tcod = { version = "0.12", features = ["serialization"] }
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
